# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b35c20c4a78da97e950036ae6654bbc1"
name = "abhi-test-app"
handle = "abhi-test-app-1"
application_url = "https://sponsors-instance-simulation-practical.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "abhimanyu-propero.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_orders,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://sponsors-instance-simulation-practical.trycloudflare.com/auth/callback",
  "https://sponsors-instance-simulation-practical.trycloudflare.com/auth/shopify/callback",
  "https://sponsors-instance-simulation-practical.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
